### ISSUE TITLE
执行main的时候报FileNotFoundError: [Errno 2] No such file or directory: 'mt-metrics-eval-v2/wmt22/sources/zh-en.txt'

### ISSUE THREAD

**Issue by qingjiaqi** [MicrosoftTranslator/GEMBA#3]
这个不是问题，我搞错了

**Comment by qingjiaqi** [comment]
搞错了

**Comment by Sara-Koni** [comment]
Hi @qingjiaqi, how did you solve this error because I'm facing the same one and I cannot figure it out why

**Comment by kocmitom** [comment]
Could it be that you forgot to download the mt-metrics-eval-v2 as per README?


git clone https://github.com/google-research/mt-metrics-eval.git
cd mt-metrics-eval
pip install .
alias mtme='python3 -m mt_metrics_eval.mtme'
mtme --download
cd ..
mv ~/.mt-metrics-eval/mt-metrics-eval-v2 mt-metrics-eval-v2
