### ISSUE TITLE
Can the sw also use GPT4T?

### ISSUE THREAD

**Issue by FritzHohl** [MicrosoftTranslator/GEMBA#5]
I tried to use a GPT4T model, but was not successful (GPT4 worked).

Maybe this is related to the old-API issue?

**Comment by kocmitom** [comment]
Yes, the tool uses an old API. Some small changes would be needed here:
https://github.com/MicrosoftTranslator/GEMBA/blob/main/gemba/gpt_api.py#L153

If you'd update it, feel free to submit a PR and I'll merge it.

**Comment by kocmitom** [comment]
Thank you Fritz for updating the code, I have commited the change, hopefully it works well for you!
