### ISSUE TITLE
CREDENTIALS

### ISSUE THREAD

**Issue by sadanyh** [MicrosoftTranslator/GEMBA#6]
Hi,

Thank you for sharing the code to your metric. I am trying to run:
`python gemba_mqm.py --source=source.txt --hypothesis=hypothesis.txt --source_lang=English --target_lang=Czech`

I added my OpenAI key in the CREDENTIALS.py in the api_key value. But I get this error:

 "Error, retrying...'gpt-4'".
 I am running my experiment in COLAB.

I am not sure if there is anything else I need to modify in the CREDENTIALS.py file besides the api_key. I am using my account in OpenAI API. Could you please help with this issue?

**Comment by kocmitom** [comment]
The last commit broke it, thank you for opening an issue. Now it should be fixed.

**Comment by sadanyh** [comment]
Thank you very much for the reply but I still get the error. FYI I just changed the api_key with my OpenAI key in the CREDENTIALS.py in the api_key value. That was done on COLAB. But I still get the same error:
<img width="987" alt="image" src="https://github.com/MicrosoftTranslator/GEMBA/assets/56395363/ac601750-939d-429f-b914-5b86f4bf262f">

**Comment by kocmitom** [comment]
It seems you don't have gpt-4 set up correctly, looks like credentials do not contain gpt-4. It should be something like this.

credentials = {
    "deployments": {"gpt-4": "the_name_you_gave_to_your_GPT4_deployment"},
    "api_base": "https://******.openai.azure.com/",
    "api_key": "********************************"
}

**Comment by sadanyh** [comment]
Thank you for your reply. I am not using it via Azure. I thought from your Repo that I can just use it through my OpenAI api account. Do I have to have to use through an Azure deployment environment?

**Comment by kocmitom** [comment]
Both are supported. However, I do not have any access to OpenAI api, so you'd need to test it yourself. However, the code should be trivial to follow and debug. If you discover a bug in the implementation, please, let me know or create PR and I'll merge it.

**Comment by CharizardAcademy** [comment]
Hi, I have the same problem here, can you pls elaborate more on how this bug can be fixed?
